name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        description: Number of days to look back for releases
        default: 3
        type: number
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          # PAT with write access to actions, code, and workflows
          # using the GITHUB_TOKEN failed as it had no workflows write permission
          # using an SSH_KEY failed creating a release
          token: ${{ secrets.TAGBOT_PAT }}
